services:
  
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: huskysiberiano
      POSTGRES_DB: my_events_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    command: /bin/sh -c "alembic upgrade head && uvicorn app.api.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
