"""Create registrations

Revision ID: d69fac703615
Revises: fe4b6cdabe04
Create Date: 2025-05-31 10:45:16.864308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69fac703615'
down_revision: Union[str, None] = 'fe4b6cdabe04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_event_id'), 'registration', ['event_id'], unique=False)
    op.create_index(op.f('ix_registration_user_id'), 'registration', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_user_id'), table_name='registration')
    op.drop_index(op.f('ix_registration_event_id'), table_name='registration')
    op.drop_table('registration')
    # ### end Alembic commands ###
